POST http://localhost:7071/api/hello
content-type: application/json

{
    "name" : "Bablu"
}

###

POST http://localhost:7071/api/copy-pbi-data
content-type: application/json

{
    "datasetId" : "8c2c0fd4-cf71-44f7-92be-4db502286acb",
    "tableName" : "Store",
    "filePath" : "/retail_analysis/stores.json"
}

###

POST http://localhost:7071/api/copy-pbi-data
content-type: application/json

{
    "datasetId" : "8c2c0fd4-cf71-44f7-92be-4db502286acb",
    "tableName" : "District",
    "filePath" : "/retail_analysis/district.json"
}
